@CadastroFuncionarios.Api_HostAddress = http://localhost:5230


### Listar funcionários
GET {{CadastroFuncionarios.Api_HostAddress}}/api/v1/funcionarios

### Buscar funcionário por id
GET {{CadastroFuncionarios.Api_HostAddress}}/api/v1/funcionarios/1

### Criar funcionário
POST {{CadastroFuncionarios.Api_HostAddress}}/api/v1/funcionarios
Content-Type: application/json

{
	"nome": "Marina Souza",
	"cargo": "Desenvolvedora Backend",
	"salario": 6500.00,
	"dataAdmissao": "2025-02-01"
}

### Atualizar funcionário
PUT {{CadastroFuncionarios.Api_HostAddress}}/api/v1/funcionarios/1
Content-Type: application/json

{
	"nome": "Marina Souza",
	"cargo": "Tech Lead",
	"salario": 8500.00,
	"dataAdmissao": "2025-02-01"
}

### Remover funcionário
DELETE {{CadastroFuncionarios.Api_HostAddress}}/api/v1/funcionarios/1
